language: go
go:
  - 1.16.x
before_install:
  - go get github.com/gertd/go-pluralize
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci